name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  push: { branches: ["master", "main"] }
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: groutoutlook
          template: classic
          # base: header, activity, community, repositories #, metadata
          # config_animations: yes
          config_timezone: Asia/Bangkok
          # plugin_traffic: yes
